"""Create initial application schema

Revision ID: b19dc377da3a
Revises: 001_initial_schema
Create Date: 2026-08-15 18:38:23.343517+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19dc377da3a'
down_revision: Union[str, Sequence[str], None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('experience_level', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('career_goal', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('applied_date', sa.String(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('career_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('overall_readiness_score', sa.Float(), nullable=True),
    sa.Column('resume_score', sa.Float(), nullable=True),
    sa.Column('job_match_score', sa.Float(), nullable=True),
    sa.Column('interview_score', sa.Float(), nullable=True),
    sa.Column('skill_depth_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('cover_letters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cover_letters_user_id'), 'cover_letters', ['user_id'], unique=False)
    op.create_table('job_targets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_targets_user_id'), 'job_targets', ['user_id'], unique=False)
    op.create_table('learning_roadmaps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_roadmaps_user_id'), 'learning_roadmaps', ['user_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('public_username', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('projects', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_portfolios_public_username'), 'portfolios', ['public_username'], unique=True)
    op.create_table('resumes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('ats_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_target_id', sa.String(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('keyword_score', sa.Float(), nullable=True),
    sa.Column('skills_score', sa.Float(), nullable=True),
    sa.Column('experience_score', sa.Float(), nullable=True),
    sa.Column('structure_score', sa.Float(), nullable=True),
    sa.Column('language_score', sa.Float(), nullable=True),
    sa.Column('matched_keywords', sa.JSON(), nullable=False),
    sa.Column('missing_keywords', sa.JSON(), nullable=False),
    sa.Column('weak_keywords', sa.JSON(), nullable=False),
    sa.Column('structural_issues', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_target_id'], ['job_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ats_analyses_job_target_id'), 'ats_analyses', ['job_target_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_target_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('overall_readiness_score', sa.Float(), nullable=True),
    sa.Column('telemetry', sa.JSON(), nullable=True),
    sa.Column('transcript', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_target_id'], ['job_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_job_target_id'), 'interview_sessions', ['job_target_id'], unique=False)
    op.create_table('job_matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_target_id', sa.String(), nullable=False),
    sa.Column('overall_match', sa.Float(), nullable=True),
    sa.Column('skills_match', sa.Float(), nullable=True),
    sa.Column('experience_match', sa.Float(), nullable=True),
    sa.Column('keyword_match', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_target_id'], ['job_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_matches_job_target_id'), 'job_matches', ['job_target_id'], unique=False)
    op.create_table('job_requirements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_target_id', sa.String(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('importance_level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_target_id'], ['job_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_requirements_job_target_id'), 'job_requirements', ['job_target_id'], unique=False)
    op.create_table('learning_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('roadmap_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('practice_task', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['learning_roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_items_roadmap_id'), 'learning_items', ['roadmap_id'], unique=False)
    op.create_table('resume_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('resume_id', sa.String(), nullable=False),
    sa.Column('version_label', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('changes_log', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_versions_resume_id'), 'resume_versions', ['resume_id'], unique=False)
    op.create_table('skill_gaps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_target_id', sa.String(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('job_requirement', sa.Text(), nullable=False),
    sa.Column('candidate_evidence', sa.Text(), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('how_to_improve', sa.Text(), nullable=False),
    sa.Column('practice_project', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_target_id'], ['job_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_gaps_job_target_id'), 'skill_gaps', ['job_target_id'], unique=False)
    op.create_index(op.f('ix_skill_gaps_skill_name'), 'skill_gaps', ['skill_name'], unique=False)
    op.create_table('user_skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('proficiency', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_skills_skill_name'), 'user_skills', ['skill_name'], unique=False)
    op.create_table('experiences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('bullets', sa.JSON(), nullable=False),
    sa.Column('tailored_bullets', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiences_version_id'), 'experiences', ['version_id'], unique=False)
    op.create_table('interview_feedbacks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('communication_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('structure_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('what_went_well', sa.JSON(), nullable=False),
    sa.Column('what_needs_work', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_feedbacks_session_id'), 'interview_feedbacks', ['session_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tech_stack', sa.JSON(), nullable=False),
    sa.Column('highlights', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_version_id'), 'projects', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_version_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_interview_feedbacks_session_id'), table_name='interview_feedbacks')
    op.drop_table('interview_feedbacks')
    op.drop_index(op.f('ix_experiences_version_id'), table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_user_skills_skill_name'), table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_index(op.f('ix_skill_gaps_skill_name'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_job_target_id'), table_name='skill_gaps')
    op.drop_table('skill_gaps')
    op.drop_index(op.f('ix_resume_versions_resume_id'), table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index(op.f('ix_learning_items_roadmap_id'), table_name='learning_items')
    op.drop_table('learning_items')
    op.drop_index(op.f('ix_job_requirements_job_target_id'), table_name='job_requirements')
    op.drop_table('job_requirements')
    op.drop_index(op.f('ix_job_matches_job_target_id'), table_name='job_matches')
    op.drop_table('job_matches')
    op.drop_index(op.f('ix_interview_sessions_job_target_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_ats_analyses_job_target_id'), table_name='ats_analyses')
    op.drop_table('ats_analyses')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_portfolios_public_username'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_learning_roadmaps_user_id'), table_name='learning_roadmaps')
    op.drop_table('learning_roadmaps')
    op.drop_index(op.f('ix_job_targets_user_id'), table_name='job_targets')
    op.drop_table('job_targets')
    op.drop_index(op.f('ix_cover_letters_user_id'), table_name='cover_letters')
    op.drop_table('cover_letters')
    op.drop_table('career_profiles')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
